#!/usr/bin/env python3
"""Emit the per-environment package files the Environments Hub expects.

`prime env push -p environments/<id>` archives only that directory, so a module
importing `creative_envs.loader` from the repository root would resolve at a
terminal here and fail for everyone who installed it from the hub. That is the
same silent wrongness these environments grade, so the generated module is
self-contained and resolves every path relative to its own file.

The source of truth is this generator. The generated files are regenerable and
should not be hand-edited.

    python3 tools/package_for_hub.py            # all environments
    python3 tools/package_for_hub.py --env ocio_config_repair

Then, with an API key set:

    prime env push -p environments/ocio_config_repair --visibility PUBLIC
"""
import argparse, json, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ENVS = os.path.join(ROOT, "environments")

# Per environment: the artifact the agent writes, the pip extras its grader
# needs, and one sentence a stranger can read on the hub listing.
SPEC = {
    "comfyui_graph_repair": {
        "artifact": "submission.json", "deps": [], "env_dir_arg": False,
        "summary": "Repair a ComfyUI API-format workflow until it validates and executes.",
        "blurb": "A workflow that loads and does the wrong thing: a dangling link, a "
                 "cycle that hangs rather than errors, a sampler feeding a node that "
                 "cannot take LATENT, a negative prompt wired into the positive encoder.",
    },
    "ocio_config_repair": {
        "artifact": "submission.ocio", "deps": ["pyyaml", "opencolorio"], "env_dir_arg": False,
        "summary": "Repair an OpenColorIO config that loads, renders, and is wrong.",
        "blurb": "Four of its five faults raise no error at all. The fifth passes every "
                 "structural check and is caught only numerically, by encoding a value "
                 "into a colourspace and decoding it back to somewhere else.",
    },
    "exr_render_repair": {
        "artifact": "submission.exr", "deps": ["numpy", "openexr"], "env_dir_arg": True,
        "summary": "Repair a render handoff that opens cleanly and is wrong.",
        "blurb": "Depth normalised to 0-1 so every defocus sits at the wrong distance. "
                 "Alpha premultiplied twice so every edge darkens. A 32-bit float file "
                 "carrying eight bits of information. Nothing errors.",
    },
    "video_conform_repair": {
        "artifact": "submission.mp4", "deps": ["numpy"], "env_dir_arg": False,
        "summary": "Repair a conform that plays cleanly and is wrong.",
        "blurb": "A conform that plays end to end and is wrong: drifting sync, a ramp "
                 "at the head, a portrait source forced into a landscape delivery.",
    },
}

MODULE = '''"""Verifiers entrypoint for {env_id}.

Generated by tools/package_for_hub.py. Do not hand-edit; regenerate instead.

The grader runs as a SUBPROCESS rather than an import, deliberately. Each one
needs a different heavy dependency, a crashed grader must not take a training run
with it, and the identical code path runs whether it is called by the container
entrypoint, by a person at a terminal, or by the RL runtime. A reward function
that behaves differently under training than it does at a terminal is the worst
failure available here, and this rules it out.
"""
import glob
import json
import os
import subprocess
import sys
import tempfile

import verifiers as vf
from datasets import Dataset

HERE = os.path.dirname(os.path.abspath(__file__))
ENV_ID = "{env_id}"
ARTIFACT = "{artifact}"
SUMMARY = "{summary}"
ENV_DIR_ARG = {env_dir_arg}


def _tasks():
    out = []
    for p in sorted(glob.glob(os.path.join(HERE, "tasks", "*.json"))):
        name = os.path.basename(p)[:-5]
        # Exclude only the shared reference, which is prefixed. An earlier
        # version also dropped anything ending "_reference" and silently ate the
        # ocio task literally named ambiguous_reference: it loaded, errored
        # nowhere, and shipped four tasks where there were five. Video's
        # per-task references are .mp4 and never match this glob.
        if name.startswith("_"):
            continue
        with open(p) as f:
            out.append((name, p, json.load(f)))
    return out


def _payload(spec):
    """Text where the artifact is text, a description where it is binary,
    because an EXR cannot be put in a prompt."""
    if "broken_graph" in spec:
        return json.dumps(spec["broken_graph"], indent=2)
    for key in ("broken_config", "broken_file"):
        if key in spec:
            p = os.path.join(HERE, "tasks", spec[key])
            if p.rsplit(".", 1)[-1] in ("exr", "mp4", "mov"):
                return (f"Binary artifact at {{spec[key]}}. Reported symptom: "
                        f"{{spec.get('symptom', 'unknown')}}")
            with open(p) as f:
                return f.read()
    return ""


def _grade(task_path, completion):
    grader = os.path.join(HERE, "tests", "grader.py")
    with tempfile.TemporaryDirectory() as tmp:
        sub = os.path.join(tmp, ARTIFACT)
        text = completion if isinstance(completion, str) else str(completion)
        binary = not ARTIFACT.endswith((".json", ".ocio", ".nk", ".txt"))
        with open(sub, "wb" if binary else "w") as f:
            f.write(text.encode("latin-1", "ignore") if binary else text)
        # A grader needs its own heavy dependency and the runtime venv may not
        # have it. Running the wrong interpreter once made the OCIO grader
        # degrade to structural-only and PASS a broken config, so the override
        # is per environment.
        interp = (os.environ.get("CREATIVE_ENVS_PY_" + ENV_ID.upper())
                  or os.environ.get("CREATIVE_ENVS_PY") or sys.executable)
        try:
            cmd = [interp, grader, "--submission", sub, "--task", task_path]
            if ENV_DIR_ARG:
                cmd += ["--env-dir", HERE]
            r = subprocess.run(cmd, capture_output=True, text=True, timeout=180)
        except subprocess.TimeoutExpired:
            return 0.0
        if r.returncode == 2:
            # Environment error rather than a failed attempt. Raising stops the
            # run instead of silently feeding zeros to every rollout.
            raise RuntimeError(
                ENV_ID + " grader cannot run: "
                + (r.stderr or r.stdout or "").strip()[:200])
    lines = (r.stdout or r.stderr or "").strip().splitlines()
    if not lines:
        return 0.0
    try:
        return float(json.loads(lines[-1]).get("reward", 0.0))
    except json.JSONDecodeError:
        return 0.0


def load_environment(**kwargs):
    instruction = ""
    p = os.path.join(HERE, "instruction.md")
    if os.path.exists(p):
        with open(p) as f:
            instruction = f.read()

    tasks = _tasks()
    if not tasks:
        raise RuntimeError("no task instances found for " + ENV_ID)

    rows, paths = [], {{}}
    for name, path, spec in tasks:
        rows.append({{
            "question": (f"{{instruction}}\\n\\n## Task: {{name}}\\n\\n"
                         f"Reported symptom: "
                         f"{{spec.get('symptom', spec.get('error', 'none'))}}\\n\\n"
                         f"```\\n{{_payload(spec)}}\\n```\\n"),
            "answer": "",
            "task": name,
        }})
        paths[name] = path

    def craft_correct(completion, answer="", **kw) -> float:
        """Binary. Partial credit would teach that a nearly-working comp is
        nearly right, which is false: it renders correctly or it does not."""
        task = kw.get("task") or kw.get("info", {{}}).get("task")
        if task not in paths:
            return 0.0
        return _grade(paths[task], completion)

    return vf.SingleTurnEnv(
        dataset=Dataset.from_list(rows),
        rubric=vf.Rubric(funcs=[craft_correct], weights=[1.0]),
        system_prompt=SUMMARY,
        **kwargs)
'''

PYPROJECT = '''[project]
name = "{pkg}"
description = "{summary}"
version = "0.1.0"
requires-python = ">=3.10"
readme = "README.md"
keywords = ["singleturn", "eval", "vfx", "creative-software"]
tags = [{tags}]
dependencies = [
  "datasets",
  "verifiers>=0.2.0",{deps}
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
include = ["{env_id}.py", "tasks/", "tests/", "instruction.md", "task.toml"]
'''

README = '''# {env_id}

{summary}

{blurb}

Every fault here is in one class: the artifact runs, raises nothing, delivers,
and is wrong. Faults that throw are already caught by the software and are not
worth grading.

## Reward

Binary, 1.0 or 0.0, with a specific reason either way. No partial credit: a
handoff is either correct for the department downstream or it is not, and
rewarding "nearly right" teaches the wrong thing efficiently.

Shape checks alone are gameable, so every channel or field the repair was not
meant to touch is compared against a known-good reference and must match, and
everything it was allowed to touch must still correlate with the original.
Satisfying the rules while destroying the data is graded as a failure. On the
first adversarial pass across these environments, seven of twelve attacks
scored full reward without fixing anything; those holes are closed and the
attacks are kept in `tools/reward_hack.py` upstream.

## Source

https://github.com/AlaboMPJ/alabo-creative-envs
'''


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--env", action="append", help="limit to one, repeatable")
    a = ap.parse_args()
    targets = a.env or sorted(SPEC)
    for env_id in targets:
        if env_id not in SPEC:
            sys.exit(f"  unknown environment {env_id}")
        cfg = SPEC[env_id]
        d = os.path.join(ENVS, env_id)
        if not os.path.isdir(d):
            print(f"  skip (no directory)  {env_id}")
            continue
        deps = "".join(f'\n  "{x}",' for x in cfg["deps"])
        tags = ", ".join(f'"{t}"' for t in
                         [env_id.split("_")[0], "vfx", "creative-software", "silent-wrongness"])
        write(os.path.join(d, f"{env_id}.py"),
              MODULE.format(env_id=env_id, artifact=cfg["artifact"],
                            summary=cfg["summary"],
                            env_dir_arg=cfg.get("env_dir_arg", False)))
        write(os.path.join(d, "pyproject.toml"),
              PYPROJECT.format(pkg=env_id.replace("_", "-"), env_id=env_id,
                               summary=cfg["summary"], deps=deps, tags=tags))
        write(os.path.join(d, "README.md"),
              README.format(env_id=env_id, summary=cfg["summary"],
                            blurb=cfg["blurb"]))
    print("\n  Then, with an API key set:\n")
    for env_id in targets:
        print(f"    prime env push -p environments/{env_id} --visibility PUBLIC")
    print()


def write(path, body):
    open(path, "w", encoding="utf-8").write(body)
    print(f"  wrote  {os.path.relpath(path, ROOT)}")


if __name__ == "__main__":
    main()
